export const TIMEZONE = "Asia/Dubai";
export const LANGUAGE = "english";
export const CURRENCY = "USD";
export const DATE_FORMAT = "DD MMM YYYY";
export const DATE_TIME_FORMAT = "DD MMM, YYYY hh:mm a";
export const TIME_FORMAT = "hh:mm a";
export const HOUR_FORMAT = "12";
export const THEME = "light";
export const ITEMS_PER_PAGE = 10;
